apiVersion: v1
appVersion: "5.3.21119"
description: A Helm chart for the Aqua Console, Gateway Components
engine: gotpl
home: https://www.aquasec.com/
icon: https://s.giantswarm.io/app-icons/1/png/aqua-app-light.png
sources:
- https://github.com/aquasecurity/aqua-helm
annotations:
    application.giantswarm.io/values-schema: https://raw.githubusercontent.com/giantswarm/aqua-app/v[[ .Version ]]/helm/aqua-app-server/values.schema.json
    application.giantswarm.io/readme: https://raw.githubusercontent.com/giantswarm/aqua-app/v[[ .Version ]]/helm/aqua-app-server/README.md
name: aqua-app-server
version: [[ .Version ]]
