{{- if .Values.web.ingress.enabled -}}
{{- $fullname := .Release.Name -}}
{{- $servicePort := .Values.gate.service.externalPort -}}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-gateway-ingress
  labels:
    app: {{ .Release.Name }}-gateway-ingress
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- if .Values.gate.ingress.annotations }}
  annotations:
{{ toYaml .Values.gate.ingress.annotations | indent 4 }}
{{- end }}
spec:
  {{ if .Values.gate.ingress.hosts }}
  rules:
    {{- range $host := (required "A valid .Values.gate.ingress.hosts entry required!" .Values.gate.ingress.hosts) }}
      - host: {{ $host }}
        http:
          paths:
            - path: /
              backend:
                serviceName: {{ $fullname }}-gateway-svc
                servicePort: {{ $servicePort }}
    {{- end -}}
  {{ else }}
  backend:
    serviceName: {{ $fullname }}-gateway-svc
    servicePort: {{ $servicePort }}
  {{ end }}
  {{- if .Values.gate.ingress.tls }}
  tls:
{{ toYaml .Values.gate.ingress.tls | indent 4 }}
  {{- end -}}
{{- end -}}
