apiVersion: v1
description: A Helm chart for the Aqua Scanner Components
engine: gotpl
home: https://www.aquasec.com/
icon: https://www.aquasec.com/wp-content/uploads/2016/05/aqua_logo_fullcolor.png
sources:
- https://github.com/aquasecurity/aqua-helm
name: aqua-app-scanner
appVersion: "4.6.0"
version: [[ .Version ]]
