apiVersion: v1
description: A Helm chart for the Aqua Scanner Components
engine: gotpl
home: https://www.aquasec.com/
icon: https://s.giantswarm.io/app-icons/1/png/aqua-app-light.png
sources:
- https://github.com/aquasecurity/aqua-helm
annotations:
    application.giantswarm.io/values-schema: https://raw.githubusercontent.com/giantswarm/aqua-app/v[[ .Version ]]/helm/aqua-app-scanner/values.schema.json
    application.giantswarm.io/readme: https://raw.githubusercontent.com/giantswarm/aqua-app/v[[ .Version ]]/README.md
name: aqua-app-scanner
appVersion: "4.6.0"
version: [[ .Version ]]
