imageCredentials:
  name: giantswarm-partner-aqua-pull-secret
  repositoryUriPrefix: "quay.io"

rbac:
  enabled: true
  roleRef:

serviceAccount: "server-sa"
server:
  serviceName: "server-console-svc"  # example
  port: 8080

image:
  repository: giantswarm/aqua-scanner
  tag: 4.5.20069
  pullPolicy: IfNotPresent

user:
password:
secretName: null
userKey: null
passwordKey: null
replicaCount: 1
livenessProbe: {}
readinessProbe: {}
resources:
  {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi
nodeSelector: {}
tolerations: []
affinity: {}
