{{- if .Values.imageCredentials.create -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-registry-secret
  labels:
    app: {{ .Release.Name }}
    chart: "{{ include "chartVersion" . }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{- end -}}
